config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_customizations/registrations',
    sessions: 'devise_customizations/sessions',
  }
  mount ActionCable.server => '/cable'

  get '/chat', to: 'chat#index'
  resources :users do
    member do
      get 'analytics_alias'
    end
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :images, only: [:create]

  namespace :admin do
    root to: 'users#index'

    resources :users do
      member do
        get 'impersonate'
        post 'test_push_notification'
      end

      collection do
        get 'stop_impersonating'
      end
    end
    resources :addresses
    resources :attachments
    resources :authentication_tokens
    resources :images
  end

  authenticated :user do
    # root to: 'dashboard#show', as: :authenticated_root
    root to: 'high_voltage/pages#show', id: 'welcome', as: :authenticated_root
  end

  devise_scope :user do
    get 'sign-in',  to: 'devise_customizations/sessions#new'
    post 'api/v1/authentication_tokens',  to: 'devise_customizations/sessions#create'
    post 'api/v1/password_resets', to: 'devise_customizations/passwords#create'

    get 'sign-out', to: 'devise/sessions#destroy'
  end
  root 'high_voltage/pages#show', id: 'welcome'

  # API-specific routes
  namespace 'api' do
    namespace 'v1' do
      jsonapi_resources :users, except: [:new, :edit]
      namespace 'users' do
        jsonapi_resources :passwords, except: [:show, :create, :index, :destroy]
      end
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?

  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ApplicationRecord
  # adds an `photo` virtual attribute
  include ::PhotoUploader::Attachment.new(:photo)

  acts_as_paranoid
  include AddressFields

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  has_many :authentication_tokens, dependent: :destroy
  has_many :addresses, as: :addressable
  has_many :messages

  before_create :generate_uuid

  attr_accessor :unencrypted_token

  # Permissions cascade/inherit through the roles listed below. The order of
  # this list is important, it should progress from least to most privelage
  ROLES = [:admin].freeze
  acts_as_user roles: ROLES
  roles ROLES

  validates :email,
            presence: true,
            format: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,8}\z/i

  # NOTE: these password validations won't run if the user has an invite token
  validates :password,
            presence: true,
            length: { within: 8..72 },
            confirmation: true,
            on: :create
  validates :password_confirmation,
            presence: true,
            on: :create

  PASSWORD_FORMAT_MESSAGE =
    'Password must be between 8 and 72 characters'.freeze

  def tester?
    (email =~ /(example.com|headway.io)$/).present?
  end

  def send_push_notification(message, type)
    rpush_app = Rpush::Apns::App.find_by(name: 'ios_app')
    return if rpush_app.blank? || device_token.blank?

    notification = Rpush::Apns::Notification.new

    notification.app = rpush_app
    notification.device_token = device_token
    notification.alert = message
    notification.data = { type: type }
    notification.save!
  end

  def name
    [first_name, last_name].join(" ")
  end

  def photo_data_uri=(uri)
    return if uri.nil?
    super(uri)
  end

  private

  def generate_uuid
    loop do
      uuid = SecureRandom.uuid
      self.uuid = uuid
      break unless User.exists?(uuid: uuid)
    end
  end
end

# rubocop:disable Metrics/LineLength, Lint/UnneededCopDisableDirective
# == Schema Information
#
# Table name: users
#
#  birthdate              :date
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  deleted_at             :datetime
#  device_token           :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  id                     :bigint(8)        not null, primary key
#  invitation_accepted_at :datetime
#  invitation_created_at  :datetime
#  invitation_limit       :integer
#  invitation_sent_at     :datetime
#  invitation_token       :string
#  invitations_count      :integer          default(0)
#  invited_by_id          :bigint(8)
#  invited_by_type        :string
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  photo_data             :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  roles_mask             :integer
#  sign_in_count          :integer          default(0), not null
#  updated_at             :datetime         not null
#  uuid                   :string
#
# Indexes
#
#  index_users_on_deleted_at                         (deleted_at)
#  index_users_on_email_and_deleted_at               (email, COALESCE(deleted_at, 'infinity'::timestamp without time zone)) UNIQUE
#  index_users_on_invitation_token                   (invitation_token) UNIQUE
#  index_users_on_invitations_count                  (invitations_count)
#  index_users_on_invited_by_id                      (invited_by_id)
#  index_users_on_invited_by_type_and_invited_by_id  (invited_by_type,invited_by_id)
#  index_users_on_reset_password_token               (reset_password_token) UNIQUE
#
# rubocop:enable Metrics/LineLength, Lint/UnneededCopDisableDirective

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    skip_before_action :require_admin!, only: [:stop_impersonating]
    respond_to :html
    load_resource

    def update
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      super
    end

    def impersonate
      user = User.find(params[:id])
      track_impersonation(user, 'Start')
      impersonate_user(user)
      redirect_to root_path
    end

    def stop_impersonating
      track_impersonation(current_user, 'Stop')
      stop_impersonating_user
      redirect_to admin_users_path
    end

    def test_push_notification
      user = User.find(params[:id])
      user.send_push_notification('Test Push Notification', 'test_message')
    end

    private

    def resource_params
      params.require(resource_name).permit(
        *dashboard.permitted_attributes,
        roles: [],
      )
    end

    def track_impersonation(user, status)
      analytics_track(
        true_user,
        "Impersonation #{status}",
        impersonated_user_id: user.id,
        impersonated_user_email: user.email,
        impersonated_by_email: true_user.email,
      )
    end
  end
end

app/controllers/api/v1/users/passwords_controller.rb
module Api
  module V1
    module Users
      class PasswordsController < ApplicationController
        include JSONAPI::Utils
        include JSONAPI::ActsAsResourceController
        skip_before_action :verify_authenticity_token

        def update
          user = User
            .accessible_by(
              Ability.new(current_user),
              params[:action].to_sym
            )
            .find_by(id: params[:id])
          authorize! :show, user
          if user.update_with_password(resource_params)
            jsonapi_render json: user
          else
            jsonapi_render_errors json: user
          end
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseApiController
      load_and_authorize_resource except: :create
      skip_authorization_check only: :create
      skip_authorize_resource only: :create
      skip_before_action :authenticate_user!, only: :create

      def index
        jsonapi_render json: User.accessible_by(Ability.new(current_user))
      end

      def show
        authorize! :show, @user
        jsonapi_render json: @user
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # https://github.com/CanCanCommunity/cancancan/wiki/authorizing-controller-actions
  # load_and_authorize_resource only: []
  skip_authorization_check only: [:analytics_alias,
                                  :edit_password,
                                  :update_password,
]

  def analytics_alias
    # view file has JS that will identify the anonymous user through segment
    # after registration via "after devise registration path"
  end

  def edit_password
    @user = User.find(current_user.id)
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user) unless true_user && true_user != @user
      flash[:notice] = 'Password successfully updated.'
      redirect_to root_path
    else
      # flash.now[:error] = 'Password not updated'
      render 'edit_password'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/views/admin/users/_collection.html.slim
/ # Collection

/ This partial is used on the `index` and `show` pages
/ to display a collection of resources in an HTML table.

/ ## Local variables:

/ - `collection_presenter`:
/   An instance of [Administrate::Page::Collection][1].
/   The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
/   the columns displayed in the table
/ - `resources`:
/   An ActiveModel::Relation collection of resources to be displayed in the table.
/   By default, the number of resources is limited by pagination
/   or by a hard limit to prevent excessive page load times

/ [1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection

table[aria-labelledby="#{table_title}"]
  thead
    tr
      - collection_presenter.attribute_types.each do |attr_name, attr_type|
        th[class="cell-label cell-label--#{attr_type.html_class} cell-label--#{collection_presenter.ordered_html_class(attr_name)}" scope="col" role="columnheader" aria-sort="#{sort_order(collection_presenter.ordered_html_class(attr_name))}"]
          = link_to(sanitized_order_params(collection_presenter, attr_name).merge(            \
            collection_presenter.order_params_for(attr_name) \
          )) do
            = t(                                                                  \
              "helpers.label.#{collection_presenter.resource_name}.#{attr_name}", \
              default: attr_name.to_s,                                            \
            ).titleize

              - if collection_presenter.ordered_by?(attr_name)
                span[class="cell-label__sort-indicator cell-label__sort-indicator--#{collection_presenter.ordered_html_class(attr_name)}"]
                  svg[aria-hidden="true"]
                    use[xlink:href="#icon-up-caret"]

      - if valid_action? :impersonate, collection_presenter.resource_name
        th[class="cell-label" scope="col" role="columnheader"] Impersonation

      - [valid_action?(:edit, collection_presenter.resource_name), \
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do
        th[scope="col"]

  tbody
    - resources.each do |resource|
      - if valid_action?(:show, collection_presenter.resource_name)
        - role = "link"
        - url = polymorphic_path([namespace, resource])
      - else
        - role = url = ''

      tr[class="js-table-row" tabindex="0" role="#{role}" data-url="#{url}"]
        - collection_presenter.attributes_for(resource).each do |attribute|
          td[class="cell-data cell-data--#{attribute.html_class}"]
            a[href="#{polymorphic_path([namespace, resource])}" class="action-show"]
              = render_field attribute

        - if valid_action? :impersonate, collection_presenter.resource_name
          td[class="cell-data"]
            a[href="#{impersonate_admin_user_path(resource.id)}"] Impersonate

        - if valid_action? :edit, collection_presenter.resource_name
          td
            = link_to(                        \
              t("administrate.actions.edit"), \
              [:edit, namespace, resource],   \
              class: "action-edit",           \
            )

        - if valid_action? :destroy, collection_presenter.resource_name
          td
            = link_to(                                             \
              t("administrate.actions.destroy"),                   \
              [namespace, resource],                               \
              class: "text-color-red",                             \
              method: :delete,                                     \
              data: { confirm: t("administrate.actions.confirm") } \
            )

app/views/admin/users/_form.html.slim
/ # Form Partial
/ This partial is rendered on a resource's `new` and `edit` pages,
/ and renders all form fields for a resource's editable attributes.

/ ## Local variables:
/ - `page`:
/   An instance of [Administrate::Page::Form][1].
/   Contains helper methods to display a form,
/   and knows which attributes should be displayed in the resource's form.
/ [1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form

= simple_form_for([namespace, page.resource], html: { class: "form" }) do |f|
  - if page.resource.errors.any?
    #error_explanation
      h2
        = t(                                                                                      \
          "administrate.form.errors",                                                             \
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")), \
          resource_name: display_resource_name(page.resource_name)                                \
        )

      ul
        - page.resource.errors.full_messages.each do |message|
          li[class="flash-error"] = message

  - page.attributes.each do |attribute|
    div[class="field-unit field-unit--#{attribute.html_class}"]
      = render_field attribute, f: f

  = render 'admin/users/role_edit', { f: f, user: page.resource, roles: User::ROLES }

  .form-actions
    = f.submit

app/views/admin/users/_password_fields.html.slim
- if user.new_record?
  = f.input :password, hint: User::PASSWORD_FORMAT_MESSAGE
  = f.input :password_confirmation

app/views/admin/users/_role_edit.html.slim
 = label_tag 'roles', 'Roles'
  - for role in roles
    = radio_button_tag "user[roles]", role, user.roles.include?(role), { name: 'user[roles][]', style: 'margin: 0px;' }
    = label_tag "user_roles_#{role}", role.to_s.humanize, style: 'position: relative; top: -5px;'

app/views/admin/users/edit.html.slim
/ # Edit

/ This view is the template for the edit page.

/ It displays a header, and renders the `_form` partial to do the heavy lifting.

/ ## Local variables:

/ - `page`:
/   An instance of [Administrate::Page::Form][1].
/   Contains helper methods to help display a form,
/   and knows which attributes should be displayed in the resource's form.

/ [1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form

- content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) }

header[class="main-content__header" role="banner"]
  h1 class="main-content__page-title"
    = content_for(:title)

  div
    = link_to(                                                        \
      t("administrate.actions.show_resource", name: page.page_title), \
      [namespace, page.resource],                                     \
      class: "button",                                                \
    ) if valid_action?(:show) && show_action?(:show, page.resource)

section[class="main-content__body"]
  = render "form", page: page

app/views/admin/users/index.html.slim
/ # Index

/ This view is the template for the index page.
/ It is responsible for rendering the search bar, header and pagination.
/ It renders the `_table` partial to display details about the resources.

/ ## Local variables:

/ - `page`:
/   An instance of [Administrate::Page::Collection][1].
/   Contains helper methods to help display a table,
/   and knows which attributes should be displayed in the resource's table.
/ - `resources`:
/   An instance of `ActiveRecord::Relation` containing the resources
/   that match the user's search criteria.
/   By default, these resources are passed to the table partial to be displayed.
/ - `search_term`:
/   A string containing the term the user has searched for, if any.
/ - `show_search_bar`:
/   A boolean that determines if the search bar should be shown.

/ [1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection

- content_for(:title) do
  = display_resource_name(page.resource_name)

header[class="main-content__header" role="banner"]
  div
    h1[class="main-content__page-title" id="page-title"]
      = content_for(:title)

  - if show_search_bar
    = render(                                                  \
      "search",                                                \
      search_term: search_term,                                \
      resource_name: display_resource_name(page.resource_name) \
    )

  div
    = link_to(                                                                    \
      "#{t("administrate.actions.new")} #{page.resource_name.titleize.downcase}", \
      [:new, namespace, page.resource_path],                                      \
      class: "button",                                                            \
    ) if valid_action? :new

section[class="main-content__body main-content__body--flush"]
  = render(                     \
    "collection",               \
    collection_presenter: page, \
    resources: resources,       \
    table_title: "page-title",  \
  )

  = paginate resources

app/views/admin/users/show.html.slim
/ # Show

/ This view is the template for the show page.
/ It renders the attributes of a resource,
/ as well as a link to its edit page.

/ ## Local variables:

/ - `page`:
  / An instance of [Administrate::Page::Show][1].
  / Contains methods for accessing the resource to be displayed on the page,
  / as well as helpers for describing how each attribute of the resource
  / should be displayed.

/ [1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show

- content_for(:title) do
  = t("administrate.actions.show_resource", name: page.page_title)

header[class="main-content__header" role="banner"]
  h1[class="main-content__page-title"]
    = content_for(:title)

  div
    = link_to( \
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource)

section[class="main-content__body"]
  dl
    - page.attributes.each do |attribute|
      dt[class="attribute-label" id="#{attribute.name}"]
        = t( \
          "helpers.label.#{resource_name}.#{attribute.name}",
          default: attribute.name.titleize,
        )

      dd[class="attribute-data attribute-data--#{attribute.html_class}"]
        = render_field attribute

section[class="main-content__supplemental"]
  = button_to "Send test push notification", \
    test_push_notification_admin_user_path(page.resource),
    style: 'margin-left: 30px;'